backend:
  name: github
  repo: TemporalAgent7/datacore
  squash_merges: true

publish_mode: editorial_workflow
media_folder: "static/media/uploads"
public_folder: "/media/uploads"
site_url: https://datacore.netlify.com

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
  - name: page
    label: Page
    folder: "static/pages"
    create: true
    fields:
      - { name: path, label: Path, required: false }
      - { name: date, label: Date, required: false, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: crew
    label: Crew
    folder: "static/crew"
    create: false
    identifier_field: name
    fields:
      - { name: rarity, label: "Crew rarity", widget: "number", min: 1, max: 5 }
      - { name: series, label: "Series", required: false }
      - { name: memory_alpha, label: "Memory Alpha URL", required: false }
      - { name: bigbook_tier, label: "BigBook Tier", widget: "number", min: 1, max: 20, required: false }
      - { name: events, label: "Events participated in", widget: "number", required: false }
      - { name: in_portal, label: "Crew available in portal", required: false, widget: boolean }
      - { name: published, label: "Published", widget: boolean }
      - { name: date, label: Date, required: false, widget: date }
      - { name: name, label: "Name" }
      - { name: body, label: Body, widget: markdown }